### ISSUE TITLE
Mail.Ru produces random exception on some websites

### ISSUE THREAD

**Issue by bologer** [bologer/anycomment.io#388]
One some website Mail.Ru authorization may produce the following exception:  
```
[28-Feb-2019 20:16:01 UTC] PHP Fatal error:  Uncaught Hybridauth\Exception\HttpRequestFailedException: Signed API request has returned an error. HTTP error 400. Raw Provider API response: {"error":{"error_msg":"Incorrect signature","error_token":"NONE","extended":null,"error_code":104}}. in /var/www/cut/data/www/domain/wp-content/plugins/anycomment/vendor/hybridauth/hybridauth/src/Adapter/AbstractAdapter.php:360
Stack trace:
#0 /var/www/cut/data/www/cut/wp-content/plugins/anycomment/vendor/hybridauth/hybridauth/src/Adapter/OAuth2.php(682): Hybridauth\Adapter\AbstractAdapter->validateApiResponse('Signed API requ...')
#1 /var/www/cut/data/www/cut/wp-content/plugins/anycomment/vendor/hybridauth/hybridauth/src/Provider/Mailru.php(71): Hybridauth\Adapter\OAuth2->apiRequest('http://www.apps...', 'GET', Array)
#2 /var/www/cut/data/www/cut/wp-content/plugins/anycomment/includes/Rest/AnyCommentSocialAuth.php(200): Hybridauth\Provider\Mailru->getUserProfile()
#3 /var/www/cut/data/www/cut in /var/www/cut/data/www/cut/wp-content/plugins/anycomment/vendor/hybridauth/hybridauth/src/Adapter/AbstractAdapter.php on line 360
```

Not sure how this can be repro, but should at least try to find it. 

Demo seems to be ok, found investigated by some user.

**Comment by bologer** [comment]
This was related to misleading message in the admin "Secret key" option which said to paste the private key, not the secret. Therefore, Mail.ru returned error as incorrect signature was sent. Closing as message was fixed in translations and in the post instructions.
